export interface ModelInfo {
  model_id: string;
  provider: string;
  name: string;
  tokenizer_type: string;
  context_window: number;
  max_output_tokens: number;
  pricing_input: number;
  pricing_output: number;
  pricing_cached_input: number;
  status: string;
  description?: string;
  tags?: string[];
}

export const DEFAULT_MODELS: ModelInfo[] = [
  {
    model_id: 'gpt-5',
    provider: 'OpenAI',
    name: 'GPT-5',
    tokenizer_type: 'o200k_base',
    context_window: 272000,
    max_output_tokens: 16384,
    pricing_input: 1.25,
    pricing_output: 5.00,
    pricing_cached_input: 0.625,
    status: 'stable',
    description: 'Next-gen flagship OpenAI model with 272k context window',
    tags: ['Flagship', 'OpenAI'],
  },
  {
    model_id: 'gpt-4o',
    provider: 'OpenAI',
    name: 'GPT-4o',
    tokenizer_type: 'o200k_base',
    context_window: 128000,
    max_output_tokens: 16384,
    pricing_input: 2.50,
    pricing_output: 10.00,
    pricing_cached_input: 1.25,
    status: 'stable',
    description: 'High-intelligence multimodal model for complex tasks',
    tags: ['Flagship', 'OpenAI'],
  },
  {
    model_id: 'o1',
    provider: 'OpenAI',
    name: 'o1',
    tokenizer_type: 'o200k_base',
    context_window: 200000,
    max_output_tokens: 100000,
    pricing_input: 15.00,
    pricing_output: 60.00,
    pricing_cached_input: 7.50,
    status: 'stable',
    description: 'Reasoning model designed to spend more time thinking',
    tags: ['Reasoning', 'OpenAI'],
  },
  {
    model_id: 'o3-mini',
    provider: 'OpenAI',
    name: 'o3-mini',
    tokenizer_type: 'o200k_base',
    context_window: 200000,
    max_output_tokens: 100000,
    pricing_input: 1.10,
    pricing_output: 4.40,
    pricing_cached_input: 0.55,
    status: 'stable',
    description: 'Fast, cost-effective reasoning model',
    tags: ['Reasoning', 'OpenAI'],
  },
  {
    model_id: 'claude-3-5-sonnet',
    provider: 'Anthropic',
    name: 'Claude 3.5 Sonnet',
    tokenizer_type: 'claude',
    context_window: 200000,
    max_output_tokens: 8192,
    pricing_input: 3.00,
    pricing_output: 15.00,
    pricing_cached_input: 0.30,
    status: 'stable',
    description: 'Anthropic flagship model for coding, reasoning, & writing',
    tags: ['Flagship', 'Anthropic'],
  },
  {
    model_id: 'claude-3-opus',
    provider: 'Anthropic',
    name: 'Claude 3 Opus',
    tokenizer_type: 'claude',
    context_window: 200000,
    max_output_tokens: 4096,
    pricing_input: 15.00,
    pricing_output: 75.00,
    pricing_cached_input: 1.50,
    status: 'stable',
    description: 'Top-level model for deep analysis and nuanced tasks',
    tags: ['Flagship', 'Anthropic'],
  },
  {
    model_id: 'claude-3-5-haiku',
    provider: 'Anthropic',
    name: 'Claude 3.5 Haiku',
    tokenizer_type: 'claude',
    context_window: 200000,
    max_output_tokens: 8192,
    pricing_input: 0.80,
    pricing_output: 4.00,
    pricing_cached_input: 0.08,
    status: 'stable',
    description: 'Ultra-fast lightweight model from Anthropic',
    tags: ['Fast', 'Anthropic'],
  },
  {
    model_id: 'gemini-2.0-flash',
    provider: 'Google',
    name: 'Gemini 2.0 Flash',
    tokenizer_type: 'gemini',
    context_window: 1048576,
    max_output_tokens: 8192,
    pricing_input: 0.10,
    pricing_output: 0.40,
    pricing_cached_input: 0.025,
    status: 'stable',
    description: 'Next-gen 1M context window model with low latency',
    tags: ['1M Context', 'Google'],
  },
  {
    model_id: 'gemini-1.5-pro',
    provider: 'Google',
    name: 'Gemini 1.5 Pro',
    tokenizer_type: 'gemini',
    context_window: 2097152,
    max_output_tokens: 8192,
    pricing_input: 1.25,
    pricing_output: 5.00,
    pricing_cached_input: 0.3125,
    status: 'stable',
    description: 'Massive 2M context window model for large codebase prompts',
    tags: ['2M Context', 'Google'],
  },
  {
    model_id: 'deepseek-v3',
    provider: 'DeepSeek',
    name: 'DeepSeek V3',
    tokenizer_type: 'deepseek',
    context_window: 128000,
    max_output_tokens: 8192,
    pricing_input: 0.27,
    pricing_output: 1.10,
    pricing_cached_input: 0.07,
    status: 'stable',
    description: 'Ultra cost-effective 671B parameter open mixture-of-experts model',
    tags: ['Open Weights', 'Cost Effective'],
  },
  {
    model_id: 'deepseek-r1',
    provider: 'DeepSeek',
    name: 'DeepSeek R1',
    tokenizer_type: 'deepseek',
    context_window: 128000,
    max_output_tokens: 8192,
    pricing_input: 0.55,
    pricing_output: 2.19,
    pricing_cached_input: 0.14,
    status: 'stable',
    description: 'State-of-the-art open reasoning model matching o1 performance',
    tags: ['Reasoning', 'Open Weights'],
  },
  {
    model_id: 'llama-3.3-70b',
    provider: 'Meta',
    name: 'Llama 3.3 70B',
    tokenizer_type: 'llama3',
    context_window: 128000,
    max_output_tokens: 4096,
    pricing_input: 0.59,
    pricing_output: 0.79,
    pricing_cached_input: 0,
    status: 'stable',
    description: 'Meta 70B open weight flagship LLM',
    tags: ['Open Weights', 'Meta'],
  },
  {
    model_id: 'qwen-2.5-72b',
    provider: 'Qwen',
    name: 'Qwen 2.5 72B',
    tokenizer_type: 'qwen2',
    context_window: 128000,
    max_output_tokens: 8192,
    pricing_input: 0.35,
    pricing_output: 0.40,
    pricing_cached_input: 0,
    status: 'stable',
    description: 'Alibaba Qwen flagship model with high multilingual capability',
    tags: ['Open Weights', 'Qwen'],
  },
  {
    model_id: 'mistral-large',
    provider: 'Mistral',
    name: 'Mistral Large 2',
    tokenizer_type: 'mistral',
    context_window: 128000,
    max_output_tokens: 4096,
    pricing_input: 2.00,
    pricing_output: 6.00,
    pricing_cached_input: 0,
    status: 'stable',
    description: 'Mistral top-tier reasoning and multilingual model',
    tags: ['European LLM', 'Mistral'],
  },
];

export const PRESET_GROUPS = [
  {
    id: 'top-flagship',
    name: 'Top Flagships',
    modelIds: ['gpt-[#0B0F17]', 'gpt-5', 'gpt-4o', 'claude-3-5-sonnet', 'gemini-2.0-flash'],
  },
  {
    id: 'open-weights',
    name: 'Open Weights Heavyweights',
    modelIds: ['deepseek-v3', 'deepseek-r1', 'llama-3.3-70b', 'qwen-2.5-72b'],
  },
  {
    id: 'high-context',
    name: 'Massive Context (>500k)',
    modelIds: ['gemini-2.0-flash', 'gemini-1.5-pro', 'gpt-5', 'claude-3-5-sonnet'],
  },
  {
    id: 'reasoning',
    name: 'Reasoning Models',
    modelIds: ['o1', 'o3-mini', 'deepseek-r1'],
  },
];
